services:
  # Backend
  - type: web
    name: speech-emotion-backend
    env: docker
    dockerContext: backend
    dockerfilePath: backend/Dockerfile
    envVars:
      - key: PYTHONIOENCODING
        value: utf-8

  # Frontend
  - type: web
    name: speech-emotion-frontend
    env: static
    buildCommand: cd frontend && npm install && npm run build
    staticPublishPath: frontend/dist
    envVars:
      - key: VITE_API_URL
        fromService:
          name: speech-emotion-backend
          type: web
          property: host
        suffix: /api